### ISSUE TITLE
Port avr-size patch to 2.33.1

### ISSUE THREAD

**Issue by anatol** [osx-cross/homebrew-avr#130]
Binutils modified size.c a lot and now it conflicts with the patch referenced here

https://github.com/osx-cross/homebrew-avr/blob/e1df340224bf42372fb922e408e516c484056dce/Formula/avr-binutils.rb#L20

Arch Linux made an attempt to port it over to 2.33.1 and the current result is here
https://git.archlinux.org/svntogit/community.git/tree/trunk/avr-size.patch?h=packages/avr-binutils

It would be great to have a unified patch across all distros to have a consistent and well-tested functionality.

**Comment by ladislas** [comment]
I'm okay with doing that. Can you locally test that the patch runs without any errors on 2.33.1?

**Comment by anatol** [comment]
The patch compiles fine with binutils 2.33.1. I tested `avr-size` locally and it looks great so far. Arch Linux also uses this patch with the test version of `avr-binutils`.

**Comment by ladislas** [comment]
Thanks @anatol! I'll change that asap unless you want to make a PR.

**Comment by ladislas** [comment]
@anatol I tried updating our patch to use the arch linux version but it failed because of different headers in the diff.

the error is here: https://dev.azure.com/osx-cross/homebrew-avr/_build/results?buildId=570&view=logs&j=f48822f6-9f12-56e2-121b-f56c97331bbb&t=d24f701f-ca91-5a58-1360-f8e5d6da5696&l=139

I fixed it by changing the header and publishing the patch on bintray.

If you'd like to work on a PR to fix that, you're welcome to do so.

**Comment by anatol** [comment]
ArchLinux uses `patch -p1 < avr-size.patch` to patch in the file. You could either:
* use `-p1` instead of `-p0` command line option
* modify lines 3/4 in my patch and remove filename prefixes `a/` and `b/`

**Comment by ladislas** [comment]
> use -p1 instead of -p0 command line option

I'll try that.

**Comment by ladislas** [comment]
So actually is was a wrong config on our side, the formula was passing `:p0`. Removing that defaulted to `:p1` and fixed the issue.

Thanks for the help @anatol!
