### ISSUE TITLE
avr-gcc@5 is needed

### ISSUE THREAD

**Issue by JohnnyXu** [osx-cross/homebrew-avr#354]
Could you put 5 back? 
I am dealing with a history project dated around 2015, which required avr-gcc at that time (my guessing is 4 or 5).  If putting 5 back is possible . Could you let know how to install  avr-gcc@5 in mac via your old version source code?

Thx
xuzhangning

**Comment by ladislas** [comment]
avr-gcc@5 has been removed because it was not possible to build bottles anymore as the dependencies are all deprecated and not maintained by hombrew/core anymore, in particular isl.

you can download the binaries here: https://github.com/osx-cross/homebrew-avr/releases/tag/avr-gcc%405-5.5.0

and this is the latest formula version before deprecation if you want to try to build it from source.

https://github.com/osx-cross/homebrew-avr/blob/c2a1249f93efa38432381c5c4b5e12b6ae47629c/Formula/avr-gcc%405.rb

I'll close the issue as we do not provide support for old deprecated and unmaintained formula. Good luck! :)
